// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: pkg/proto/assistant/v1/assistant.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_pkg_proto_assistant_v1_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_assistant_v1_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_assistant_v1_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TextResponse  string                 `protobuf:"bytes,2,opt,name=text_response,json=textResponse,proto3" json:"text_response,omitempty"`
	AudioData     []byte                 `protobuf:"bytes,3,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	IsFinal       bool                   `protobuf:"varint,4,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_pkg_proto_assistant_v1_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_assistant_v1_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_assistant_v1_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetTextResponse() string {
	if x != nil {
		return x.TextResponse
	}
	return ""
}

func (x *ChatResponse) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *ChatResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_pkg_proto_assistant_v1_assistant_proto protoreflect.FileDescriptor

const file_pkg_proto_assistant_v1_assistant_proto_rawDesc = "" +
	"\n" +
	"&pkg/proto/assistant/v1/assistant.proto\x12\fassistant.v1\"e\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\"\x8c\x01\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rtext_response\x18\x02 \x01(\tR\ftextResponse\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x03 \x01(\fR\taudioData\x12\x19\n" +
	"\bis_final\x18\x04 \x01(\bR\aisFinal2U\n" +
	"\x10AssistantService\x12A\n" +
	"\x04Chat\x12\x19.assistant.v1.ChatRequest\x1a\x1a.assistant.v1.ChatResponse(\x010\x01B/Z-github.com/evisdrenova/ember-server/pkg/protob\x06proto3"

var (
	file_pkg_proto_assistant_v1_assistant_proto_rawDescOnce sync.Once
	file_pkg_proto_assistant_v1_assistant_proto_rawDescData []byte
)

func file_pkg_proto_assistant_v1_assistant_proto_rawDescGZIP() []byte {
	file_pkg_proto_assistant_v1_assistant_proto_rawDescOnce.Do(func() {
		file_pkg_proto_assistant_v1_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_assistant_v1_assistant_proto_rawDesc), len(file_pkg_proto_assistant_v1_assistant_proto_rawDesc)))
	})
	return file_pkg_proto_assistant_v1_assistant_proto_rawDescData
}

var file_pkg_proto_assistant_v1_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_assistant_v1_assistant_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: assistant.v1.ChatRequest
	(*ChatResponse)(nil), // 1: assistant.v1.ChatResponse
}
var file_pkg_proto_assistant_v1_assistant_proto_depIdxs = []int32{
	0, // 0: assistant.v1.AssistantService.Chat:input_type -> assistant.v1.ChatRequest
	1, // 1: assistant.v1.AssistantService.Chat:output_type -> assistant.v1.ChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_assistant_v1_assistant_proto_init() }
func file_pkg_proto_assistant_v1_assistant_proto_init() {
	if File_pkg_proto_assistant_v1_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_assistant_v1_assistant_proto_rawDesc), len(file_pkg_proto_assistant_v1_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_assistant_v1_assistant_proto_goTypes,
		DependencyIndexes: file_pkg_proto_assistant_v1_assistant_proto_depIdxs,
		MessageInfos:      file_pkg_proto_assistant_v1_assistant_proto_msgTypes,
	}.Build()
	File_pkg_proto_assistant_v1_assistant_proto = out.File
	file_pkg_proto_assistant_v1_assistant_proto_goTypes = nil
	file_pkg_proto_assistant_v1_assistant_proto_depIdxs = nil
}
